"""empty message

Revision ID: 1f690c278ea2
Revises: 7e65c7a55431
Create Date: 2024-07-22 22:30:54.612300

"""
from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision = '1f690c278ea2'
down_revision = '7e65c7a55431'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nodo_arbol', schema=None) as batch_op:
        batch_op.drop_column('embedding')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nodo_arbol', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=3), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
