"""empty message

Revision ID: 1fd16dd13b52
Revises: e73400b52199
Create Date: 2024-07-23 09:58:10.930510

"""
from alembic import op
import sqlalchemy as sa
import pgvector

# revision identifiers, used by Alembic.
revision = '1fd16dd13b52'
down_revision = 'e73400b52199'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodo_arbol',
    sa.Column('nodoID', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.PrimaryKeyConstraint('nodoID')
    )
    op.create_table('usuario',
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('conocimiento_usuario',
    sa.Column('usuario_email', sa.String(length=250), nullable=False),
    sa.Column('nodoID', sa.Integer(), nullable=False),
    sa.Column('nivel_IA', sa.Integer(), nullable=True),
    sa.Column('nivel_validado', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['nodoID'], ['nodo_arbol.nodoID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_email'], ['usuario.email'], ),
    sa.PrimaryKeyConstraint('usuario_email', 'nodoID')
    )
    op.create_table('relaciones_nodo',
    sa.Column('ascendente_id', sa.Integer(), nullable=False),
    sa.Column('descendente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ascendente_id'], ['nodo_arbol.nodoID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['descendente_id'], ['nodo_arbol.nodoID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ascendente_id', 'descendente_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relaciones_nodo')
    op.drop_table('conocimiento_usuario')
    op.drop_table('usuario')
    op.drop_table('nodo_arbol')
    # ### end Alembic commands ###
