"""empty message

Revision ID: 7e65c7a55431
Revises: b48337fd2967
Create Date: 2024-07-22 22:28:50.159433

"""
from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision = '7e65c7a55431'
down_revision = 'b48337fd2967'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nodo_arbol', schema=None) as batch_op:
        batch_op.alter_column('embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=3),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nodo_arbol', schema=None) as batch_op:
        batch_op.alter_column('embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=3),
               existing_nullable=True)

    # ### end Alembic commands ###
