"""empty message

Revision ID: 8e9f1003a051
Revises: 70d094fd73d1
Create Date: 2024-07-04 16:06:01.657461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e9f1003a051'
down_revision = '70d094fd73d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conocimiento_usuario', schema=None) as batch_op:
        batch_op.drop_constraint('conocimiento_usuario_nodoID_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'nodo_arbol', ['nodoID'], ['nodoID'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conocimiento_usuario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('conocimiento_usuario_nodoID_fkey', 'nodo_arbol', ['nodoID'], ['nodoID'])

    # ### end Alembic commands ###
