"""empty message

Revision ID: b48337fd2967
Revises: f7e9e9554004
Create Date: 2024-07-22 19:03:14.812209

"""
from alembic import op
import pgvector
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b48337fd2967'
down_revision = 'f7e9e9554004'
branch_labels = None
depends_on = None



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nodo_arbol', schema=None) as batch_op:
        batch_op.alter_column('embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=3),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nodo_arbol', schema=None) as batch_op:
        batch_op.alter_column('embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=3),
               existing_nullable=True)

    # ### end Alembic commands ###
