"""empty message

Revision ID: c72cccf7099d
Revises: 
Create Date: 2024-06-23 17:35:35.146142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c72cccf7099d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodo_arbol',
    sa.Column('nodoID', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('nodoID')
    )
    op.create_table('usuario',
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('relaciones_nodo',
    sa.Column('ascendente_id', sa.Integer(), nullable=False),
    sa.Column('descendente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ascendente_id'], ['nodo_arbol.nodoID'], ),
    sa.ForeignKeyConstraint(['descendente_id'], ['nodo_arbol.nodoID'], ),
    sa.PrimaryKeyConstraint('ascendente_id', 'descendente_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relaciones_nodo')
    op.drop_table('usuario')
    op.drop_table('nodo_arbol')
    # ### end Alembic commands ###
