"""empty message

Revision ID: e73400b52199
Revises: 1f690c278ea2
Create Date: 2024-07-22 22:31:52.217606

"""
from alembic import op
import sqlalchemy as sa
import pgvector

# revision identifiers, used by Alembic.
revision = 'e73400b52199'
down_revision = '1f690c278ea2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nodo_arbol', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nodo_arbol', schema=None) as batch_op:
        batch_op.drop_column('embedding')

    # ### end Alembic commands ###
