"""empty message

Revision ID: e7d5e397eabf
Revises: 8e9f1003a051
Create Date: 2024-07-04 16:27:22.824236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7d5e397eabf'
down_revision = '8e9f1003a051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relaciones_nodo', schema=None) as batch_op:
        batch_op.drop_constraint('relaciones_nodo_ascendente_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('relaciones_nodo_descendente_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'nodo_arbol', ['ascendente_id'], ['nodoID'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'nodo_arbol', ['descendente_id'], ['nodoID'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relaciones_nodo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('relaciones_nodo_descendente_id_fkey', 'nodo_arbol', ['descendente_id'], ['nodoID'])
        batch_op.create_foreign_key('relaciones_nodo_ascendente_id_fkey', 'nodo_arbol', ['ascendente_id'], ['nodoID'])

    # ### end Alembic commands ###
