"""empty message

Revision ID: f7e9e9554004
Revises: e7d5e397eabf
Create Date: 2024-07-22 14:12:41.286109

"""
from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision = 'f7e9e9554004'
down_revision = 'e7d5e397eabf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nodo_arbol', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=3), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nodo_arbol', schema=None) as batch_op:
        batch_op.drop_column('embedding')

    # ### end Alembic commands ###
